language: python
python:
  - "3.7"

install:
  - pip install -r "requirements.txt"

script:
  - python3 manage.py test 

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIA6HSYUFZQTNQLX4EM"
  secret_access_key:
    secure: "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"
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-978364673633"
  on:
    all_brances: true