language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python3 manage.py test 

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-978364673633"
  on:
    all_brances: true